[project]
name = "smqa-coursework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "coverage>=7.13.0",
    "pynguin>=0.44.0",
]
